[package]
name = "breezy1214/zoneplus"
description = "Construct dynamic zones that utilise region checking, raycasting and the new BasePart.CanTouch property to effectively determine players and parts within their boundaries."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "4.0.1"
exclude = [
	"docs", ".moonwave", "test",
	"ZonePlus.rbxm", "ZonePlus.rbxmx",
	".gitignore", "foreman.toml",
]

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
Signal = "sleitnick/signal@2.0.1"